services:
  backend:
    image: ${COMPOSE_PROJECT_NAME}-backend:dev
    container_name: ${COMPOSE_PROJECT_NAME}-backend

    restart: unless-stopped

    # Inject all environment variables from backend/.env into the container
    env_file:
      - backend/.env

    build:
      # Send the content in /backend to daemon
      context: ./backend

    ports:
      - "${BACKEND_PORT}:8000"

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    volumes:
      # Host: /backend
      # Container: /app (defined in Dockerfile)
      - ./backend:/app

  nginx:
    image: nginx:stable-alpine3.24
    container_name: ${COMPOSE_PROJECT_NAME}-nginx

    restart: unless-stopped

    ports:
      - "${NGINX_PORT}:80"

    volumes:
      # :ro -> read-only
      # Nginx configuration
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro

      # Static and media files
      - ./backend/src/staticfiles:/app/src/staticfiles:ro
      - ./backend/src/media:/app/src/media:ro

    depends_on:
      - backend

  celery-worker:
    image: ${COMPOSE_PROJECT_NAME}-backend:dev
    container_name: ${COMPOSE_PROJECT_NAME}-worker

    restart: unless-stopped

    # Inject all environment variables from backend/.env into the container
    env_file:
      - backend/.env

    build:
      context: ./backend

    command: celery -A app worker --loglevel=info

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    volumes:
      - ./backend:/app

  celery-beat:
    image: ${COMPOSE_PROJECT_NAME}-backend:dev
    container_name: ${COMPOSE_PROJECT_NAME}-beat

    restart: unless-stopped

    # Inject all environment variables from backend/.env into the container
    env_file:
      - backend/.env

    build:
      context: ./backend

    command: celery -A app beat --loglevel=info

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy

    volumes:
      - ./backend:/app

  postgres:
    image: postgres:17
    container_name: ${COMPOSE_PROJECT_NAME}-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "${POSTGRES_HOST_PORT}:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      # Check whether PostgreSQL is ready
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]

      # Check every 5 seconds
      interval: 3s

      # Maximum time for each check
      timeout: 5s

      # Retry 5 times
      retries: 5

      # Grace period while PostgreSQL starts
      start_period: 10s

  redis:
    image: redis:7.4.9-alpine
    container_name: ${COMPOSE_PROJECT_NAME}-redis

    restart: unless-stopped

    ports:
      - "${REDIS_HOST_PORT}:6379"

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
