# Python 3.13 slim as the base image.
# Most common option, only needed requirements and excellent compatibility.
FROM python:3.13-slim

# Python best practices
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the default working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libatomic1 \
    && rm -rf /var/lib/apt/lists/*

# Host: backend/requirements.txt
# Container /app/requirements.txt
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Host: backend/entrypoint.sh
# Container /app/entrypoint.sh
COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]

WORKDIR /app/src

# Development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
