# Python 3.13 slim as the base image.
# Most common option, only needed requirements and excellent compatibility.
FROM python:3.13-slim

# Set the default working folder
WORKDIR /app

CMD ["python", "--version"]