# Generated by Django 5.2.6 on 2026-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(fields=('stripe_customer', 'stripe_price_id'), name='unique_subscription_per_customer_price'),
        ),
    ]
