# Generated by Django 5.2.6 on 2026-09-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_unique_subscription_per_customer_price'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_subscription_per_customer_price',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.CharField(default='pro-lifetime', max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'active'])), fields=('stripe_customer', 'plan'), name='unique_open_subscription_per_customer_plan'),
        ),
    ]
