#Virtual host configuration for the application.

server {
    listen 80;
    server_name localhost;
    location / {
        proxy_pass http://backend:8000;

        # send client host
        proxy_set_header Host $host;
    }
}
