# Generated by Django 5.2.6 on 2026-08-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_user_is_phone_verified_user_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
