# Generated by Django 5.2.6 on 2026-08-25 16:48

import django.core.validators
from django.db import migrations, models

import app.authentication.validators


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_socialaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to="avatars/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    app.authentication.validators.validate_avatar_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="socialaccount",
            name="provider",
            field=models.CharField(
                choices=[("google", "Google"), ("github", "Github")], max_length=50
            ),
        ),
    ]
