# Generated by Django 5.2.6 on 2026-09-22 13:17

import django.core.validators
from django.db import migrations, models

import app.authentication.models.user
import app.authentication.validators


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_avatar_alter_socialaccount_provider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                upload_to=app.authentication.models.user.avatar_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    app.authentication.validators.validate_avatar_size,
                ],
            ),
        ),
    ]
