name: Build and Test

on:
  # Run the workflow manually in Github
  workflow_dispatch:

  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  quality:
    name: Code Quality

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Prepare environment
        run: cp .env.ci .env

      - name: Build Docker images
        run: make build

      - name: Run Ruff
        run: make backend-ci-lint

      - name: Run Pyright
        run: make backend-ci-type-check

      - name: Run Pytest
        run: make backend-ci-test

      - name: Stop Docker containers
        if: always()
        run: make stop
